{"pageProps":{"questions":[{"id":"BSzhOlgO2RRTg7ISlUZW","timestamp":"2021-10-09 10:20:00","answer_description":"","isMC":true,"answer_images":[],"answers_community":["C (35%)","A (35%)","B (29%)"],"url":"https://www.examtopics.com/discussions/python-institute/view/63851-exam-pcap-topic-1-question-80-discussion/","question_text":"What is the expected behavior of the following code?\n//IMG//","question_id":121,"choices":{"A":"it outputs 3","C":"the code is erroneous and it will not execute","D":"it outputs 2","B":"it outputs 1"},"exam_id":192,"answer":"C","answer_ET":"C","topic":"1","discussion":[{"poster":"it_man_531","content":"Selected Answer: C\n\"C\" is correct answer.\ncolon is missing in except ArithmeticError hence it will return a SyntaxError","timestamp":"1643763360.0","comment_id":"538284","upvote_count":"5"},{"content":"Selected Answer: B\nB, the question is incorrect. \n\nm = 0\n\n\ndef foo(n):\n global m\n assert m != 0\n\n try:\n return 1/n # 1/0 is ZeroDivisionError\n except ArithmeticError:\n raise ValueError\n\n\ntry:\n foo(0)\nexcept ArithmeticError:\n m += 2\nexcept:\n m += 1 # Because is ZeroDivisionError, 0+1= 1\n\nprint(m) # Print 1","upvote_count":"5","comment_id":"868228","timestamp":"1681297500.0","poster":"aferiver"},{"upvote_count":"1","content":"Selected Answer: A\nA is coorect","comment_id":"1301150","timestamp":"1729527720.0","poster":"46a1b89"},{"comment_id":"1137067","poster":"zantrz","content":"Selected Answer: A\nThe answer is A.\nm = 0\ndef foo(n):\n global m\n assert m == 0 #raises an AssertionError if m is equal to 0. This is a check to ensure that m is zero.\n try:\n return 1/n\n except ArithmeticError: #there is ZeroDivisionError so m will be 0+1 = 1\n m+=1\n raise #if we add \"raise\" we get the exception error\n\n\ntry: #the outer try block calls the foo(0) function, which will raise an ArithmeticError (precisily ZeroDivisionError)\n foo(0)\nexcept ArithmeticError: #this block will be executed\n m +=2 # so we add 1 +2 = 3\nexcept:\n m +=1 #If any other exception occurs, m is incremented by 1, and the current value of m is printed. In case of foo(0) this block will not be executed.\n\nprint(m) # Prints 3","timestamp":"1706728680.0","upvote_count":"1"},{"timestamp":"1702635660.0","poster":"codedatakage","upvote_count":"3","comment_id":"1097193","content":"Selected Answer: A\nI have implemented the code, and I get the answer \"A\". I write here the code to help to test it.\n\nm = 0\ndef foo(n):\n global m\n assert m==0\n try:\n return 1/n\n except ArithmeticError:\n m+=1\n raise\n\ntry:\n foo(0)\nexcept ArithmeticError:\n m+=2\nexcept:\n m+=1\nprint(m)# print: 3"},{"poster":"Ujjal_d","comment_id":"987401","timestamp":"1692704280.0","content":"Selected Answer: C\nWhich is correct?","upvote_count":"1"},{"content":"the awnser its C SyntaxError: 'return' outside function\nand its 1 /n and the its global m = 0 and not n","timestamp":"1692164340.0","poster":"emanuelcar990","upvote_count":"1","comment_id":"982217"},{"comment_id":"890167","timestamp":"1683305100.0","poster":"swatiphadtare","content":"If code doesnt have type then answer is D\n\nm = 0\ndef foo(n):\n global m\n assert m == 0\n try:\n return 1/n\n except ArithmeticError:\n m=m+1\n raise ValueError\ntry:\n foo(0)\nexcept ArithmeticError:\n m +=2\nexcept:\n m +=1\nprint(m) # Prints 2","upvote_count":"1"},{"content":"Selected Answer: A\nA.\nTwo arithmetic errors. The 'raise' in the example doesn't specify an error so it continues handling a 'ZeroDivisionError'. (This all assumes the second colon is put in of course)","upvote_count":"1","poster":"Mallie","comment_id":"763606","timestamp":"1672650000.0"},{"upvote_count":"2","content":"If it wasnt for Type Error, Answer is A.","poster":"Jnanada","timestamp":"1660851600.0","comment_id":"648597"},{"timestamp":"1655320740.0","content":"A if ':' after except ArithmeticError else SyntaxError. 1/0 will raise ZeroDivision error which will be caught by the ArithmeticError at both levels with a m sum of 3.","poster":"stuartz","comment_id":"616921","upvote_count":"5"},{"poster":"ahuja","upvote_count":"1","comment_id":"526912","content":"Answer is A: 1, it throws AssertionError, hence goes to m+=1","timestamp":"1642530120.0"},{"comment_id":"504432","upvote_count":"3","content":"Answer is C\n\nThe real exam has :\nexcept ArithmeticError:\n\nm = 0\n\ndef foo(n):\n global m\n assert m != 0\n try:\n return 1/n\n except ArithmeticError:\n raise ValueError\n\ntry:\n foo(0)\nexcept ArithmeticError:\n m +=2\nexcept:\n m +=1\nprint(m) # Print 1","timestamp":"1639856880.0","poster":"DTL001"},{"upvote_count":"3","content":"A is correct","timestamp":"1633767600.0","comment_id":"459548","poster":"vlobachevsky","comments":[{"upvote_count":"2","timestamp":"1634733120.0","content":"agree, but only in case:\n\nexcept ArithmeticError had \":\" on the end. Without \":\" it will return SyntaxError","comment_id":"465150","poster":"mazimir"}]}],"question_images":["https://www.examtopics.com/assets/media/exam-media/04235/0005300001.png"],"unix_timestamp":1633767600},{"id":"U48Kp4bKzX1lnTAm2d97","isMC":true,"question_images":["https://www.examtopics.com/assets/media/exam-media/04235/0005500001.png"],"question_id":122,"topic":"1","answers_community":["C (100%)"],"question_text":"What is the expected behavior of the following code?\n//IMG//","answer_description":"","discussion":[{"upvote_count":"1","poster":"seaverick","comment_id":"1134033","content":"Selected Answer: C\ns='2A'\ntry:\n n=int(s)\nexcept TypeError:\n n=3\nexcept LookupError:\n n=2\nexcept:\n n=1\nprint(n)\n\nAns is C","timestamp":"1706440920.0"},{"poster":"macxsz","content":"Selected Answer: C\nC. it outputs 1","upvote_count":"1","comment_id":"596405","timestamp":"1651585620.0"},{"upvote_count":"4","poster":"lukaki","content":"This is ValueError, thus 'except' will be executed. It means answer is C","timestamp":"1637871240.0","comment_id":"486913"}],"answer_images":["https://www.examtopics.com/assets/media/exam-media/04235/0005600001.jpg"],"answer":"C","exam_id":192,"answer_ET":"C","url":"https://www.examtopics.com/discussions/python-institute/view/66730-exam-pcap-topic-1-question-81-discussion/","choices":{"A":"it outputs 3","C":"it outputs 1","D":"it outputs 2","B":"the code is erroneous and it will not execute"},"timestamp":"2021-11-25 21:14:00","unix_timestamp":1637871240},{"id":"rgUuOu0Hbi4OivJZo0m4","answer_images":["https://www.examtopics.com/assets/media/exam-media/04235/0005800001.jpg"],"answers_community":[],"topic":"1","answer_description":"","question_text":"Which of the following snippets will execute without raising any unhandled exceptions? (Choose two.)\nA.\n//IMG//\n\nB.\n//IMG//\n\nC.\n//IMG//\n\nD.\n//IMG//","answer_ET":"AC","question_id":123,"url":"https://www.examtopics.com/discussions/python-institute/view/64565-exam-pcap-topic-1-question-82-discussion/","isMC":false,"discussion":[{"upvote_count":"6","comment_id":"504493","poster":"DTL001","content":"Correct Answer: AC.","timestamp":"1639866540.0"},{"timestamp":"1660854480.0","comment_id":"648615","upvote_count":"5","poster":"Jnanada","content":"Correct Answer AC\nB - ValueError will be thrown."},{"comment_id":"1133462","content":"try:\n print(0/0)\nexcept:\n print(0/1)\nelse:\n print(0/2)\n \n#try:\n# print(int(\"0\"))\n#except NameError:\n# print(\"0\")\n#else:\n# print(int(\"\"))#ValueError: invalid literal for int() with base 10: ''\n\nimport math\ntry:\n print(math.sqrt(-1))\nexcept:\n print(math.sqrt(0))\nelse:\n print(math.sqrt(1))\n \n#try:\n# print(float(\"1e1\"))\n#except (NameError, SystemError):\n# print(float(\"1a1\"))\n#else:\n# print(float(\"1c1\"))#ValueError: could not convert string to float: '1c1'\n\nAns is A,C","timestamp":"1706370540.0","poster":"seaverick","upvote_count":"1"},{"timestamp":"1664225220.0","upvote_count":"2","content":"B: ----> 6 print(int(\"\"))\n\nValueError: invalid literal for int() with base 10: ''\n\nC:----> 6 print(float(\"1c1\"))\n\nValueError: could not convert string to float: '1c1'","comment_id":"680145","poster":"Dav023"},{"poster":"macxsz","upvote_count":"1","content":"Answer: BC","comment_id":"596406","comments":[{"timestamp":"1651585860.0","comment_id":"596407","poster":"macxsz","content":"sorry, answer is A and C","upvote_count":"5"}],"timestamp":"1651585740.0"},{"comment_id":"488838","upvote_count":"2","poster":"dhikra","timestamp":"1638074760.0","content":"i think answer BC !!"},{"timestamp":"1634989620.0","poster":"luckymuki","comments":[{"upvote_count":"1","content":"You're right, that snippet prints 0 and doesn't raise any exception.","comment_id":"473331","poster":"Misco33","timestamp":"1636186380.0"},{"poster":"VigneshVj","upvote_count":"5","content":"In B,else block will be executed and it will throw \"ValueError: invalid literal for int() with base 10: ''\"","comment_id":"484107","timestamp":"1637578860.0"}],"upvote_count":"2","content":"What is wrong with answer B? Looks like correct option as well","comment_id":"466539"}],"timestamp":"2021-10-23 13:47:00","answer":"AC","unix_timestamp":1634989620,"question_images":["https://www.examtopics.com/assets/media/exam-media/04235/0005600002.png","https://www.examtopics.com/assets/media/exam-media/04235/0005700001.png","https://www.examtopics.com/assets/media/exam-media/04235/0005700002.png","https://www.examtopics.com/assets/media/exam-media/04235/0005700003.png"],"exam_id":192},{"id":"k1P3N77GHUrZaSmXDiSX","answers_community":["C (100%)"],"question_text":"What is the expected behavior of the following code?\n//IMG//","question_images":["https://www.examtopics.com/assets/media/exam-media/04235/0005800002.png"],"topic":"1","choices":{"D":"the code is erroneous and it will not execute","A":"it outputs error","C":"it outputs list assignment index out of range","B":"it outputs <class 'IndexError'>"},"answer_ET":"C","answer":"C","isMC":true,"question_id":124,"answer_description":"","discussion":[{"content":"Selected Answer: C\nlist assignment index out of range","timestamp":"1664225400.0","comment_id":"680147","upvote_count":"1","poster":"Dav023"},{"timestamp":"1657471500.0","comment_id":"629644","upvote_count":"2","poster":"James_111","content":"C: outputs list assignment index out of range. \nThis is because \nmy_list = [1, 2, 3]\n(# is positioned as 0,1,2) so having a [3] would need the list to me longer my_list=[1, 2, 3, 4]"},{"content":"Selected Answer: C\nC. it outputs list assignment index out of range","upvote_count":"1","poster":"macxsz","timestamp":"1651585980.0","comment_id":"596410"}],"timestamp":"2022-05-03 15:53:00","url":"https://www.examtopics.com/discussions/python-institute/view/75121-exam-pcap-topic-1-question-83-discussion/","answer_images":["https://www.examtopics.com/assets/media/exam-media/04235/0005900001.jpg"],"exam_id":192,"unix_timestamp":1651585980},{"id":"aSAOWhGyXnRyMBmmbhH4","timestamp":"2021-10-25 14:15:00","topic":"1","unix_timestamp":1635164100,"url":"https://www.examtopics.com/discussions/python-institute/view/64697-exam-pcap-topic-1-question-84-discussion/","discussion":[{"content":"Selected Answer: BC\nB. the string I feel fine will be seen - it happens before any exception is raised\nC. unhandled exception is raised and writes down \"Exception: what a pity\", not only \"what a pity\" as the answer D states","upvote_count":"7","timestamp":"1668499980.0","comment_id":"718583","poster":"rotimislaw"},{"content":"Selected Answer: BD\nB.D. watch video. Answer broken down at 47 minutes. https://www.youtube.com/watch?v=Tme3Op1_IPk","comment_id":"1211524","upvote_count":"1","timestamp":"1715700720.0","poster":"CoinUmbrella"},{"content":"The code could also be like this perhaps\nclass E(Exception):\n def __init__(self, message):\n self.message = message\n\n def __str__(self):\n return \"It's nice to see you\"\n\ntry:\n print(\"I feel fine\")\n raise Exception(\"what a pity\")\nexcept Exception as e:\n print(e)\nelse:\n print(\"the show must go on\")","upvote_count":"1","timestamp":"1707239940.0","comment_id":"1142401","poster":"Damon54"},{"poster":"zantrz","timestamp":"1706788020.0","comment_id":"1137579","upvote_count":"1","content":"Selected Answer: BC\nThe raise Exception(\"What a pity\") line raises a generic Exception, not an instance of the custom exception E. Since the except E as e block is specifically looking for instances of E, it won't catch the raised exception, and the control will go directly to the else block.\nHowever!\nThe program terminates abruptly after encountering the unhandled Exception, and the else block doesn't get a chance to execute. When an unhandled exception occurs, the normal program flow is disrupted, and subsequent code (including the else block) is skipped.\n\nTo make the else block execute, you would need to handle the exception, either by catching it with the correct except block or allowing the program to handle it at a higher level."},{"upvote_count":"1","timestamp":"1693125660.0","comment_id":"991303","poster":"mplopez","content":"Selected Answer: BD\nThe B option is correct because the string I feel fine is printed on screen, and the D option is printed too."},{"content":"Selected Answer: BD\nB. the string I feel fine will be seen\nD. the string what a pity will be seen","poster":"macxsz","timestamp":"1651586040.0","comment_id":"596412","upvote_count":"3"},{"upvote_count":"3","timestamp":"1646572980.0","poster":"TheNetworkStudent","content":"Selected Answer: BD\nAlthough answer B, C and D are correct. I think B and D are the 'best' answers.\n\nBecause C an unhandled exception is raised, D is true. B is true because the line is printed before C and D happen.","comment_id":"562032"},{"poster":"sadako11","upvote_count":"1","content":"the message 'I fell fine' will be seen and\nthe code will raise an unhandled exception and the message 'what a pity ' will be seen.\nThe answers could be B,C or D","timestamp":"1644960300.0","comment_id":"548067"},{"poster":"DTL001","comment_id":"504508","content":"Answer in BD, I've tested:\n\n\nclass E(Exception):\n def __init__(self, message):\n self.message = message\n def __str__(self):\n return \"It's nice to see you\"\n\ntry:\n print(\"I fell fine\")\n raise Exception(\"What a party\")\nexcept E as e:\n print(e)\nelse:\n print(\"the show must go on\")\n\n#Output:\n#I fell fine\n\n#Traceback (most recent call last):\n# File \"C:\\devops\\python\\t.py\", line 9, in <module>\n# raise Exception(\"What a party\")\n#Exception: What a party","upvote_count":"2","timestamp":"1639869360.0"},{"content":"The answer is B,C","comments":[{"upvote_count":"1","content":"It actually is BD. The string \"what a pity\" is the error message displayed so technically it will be seen along with \"I feel fine\".","comment_id":"493938","poster":"techdawgs","timestamp":"1638648720.0"}],"poster":"luckymuki","upvote_count":"3","timestamp":"1635164100.0","comment_id":"467447"}],"answer_images":[],"answer_description":"","question_text":"What is true about the following snippet? (Choose two.)\n//IMG//","isMC":true,"choices":{"D":"the string what a pity will be seen","C":"the code will raise an unhandled exception","A":"the string it's nice to see you will be seen","B":"the string I feel fine will be seen"},"answer_ET":"BD","answers_community":["BD (50%)","BC (50%)"],"exam_id":192,"question_images":["https://www.examtopics.com/assets/media/exam-media/04235/0006000001.png"],"question_id":125,"answer":"BD"}],"exam":{"isBeta":false,"numberOfQuestions":141,"id":192,"lastUpdated":"12 Apr 2025","isMCOnly":false,"isImplemented":true,"name":"PCAP","provider":"Python-institute"},"currentPage":25},"__N_SSP":true}