{"pageProps":{"questions":[{"id":"nfVBIqLOPOkFQ8DMShsV","unix_timestamp":1727336220,"url":"https://www.examtopics.com/discussions/python-institute/view/148110-exam-pcep-30-02-topic-5-question-285-discussion/","answer_description":"","exam_id":194,"timestamp":"2024-09-26 09:37:00","isMC":true,"choices":{"B":"","E":"","D":"","F":"","A":"","C":""},"question_id":271,"question_text":"Which of the following snippets shows the correct way of handling multiple exceptions in a single except clause?","answers_community":["C (67%)","B (33%)"],"question_images":[],"topic":"5","answer":"C","discussion":[{"poster":"akumo","content":"Selected Answer: C\nC is the answer","timestamp":"1742497800.0","upvote_count":"1","comment_id":"1401284"},{"timestamp":"1738005480.0","upvote_count":"1","comment_id":"1347533","poster":"Sam_sgv","content":"Selected Answer: C\nYou can list multiple exception types within parentheses after except"},{"poster":"Billybob0604","content":"Selected Answer: C\n1 exception\nexcept ZeroDivisonError :\n2 exceptions\nexcept (TypeError, ValueError) :","upvote_count":"2","comment_id":"1317707","timestamp":"1732561380.0"},{"content":"Selected Answer: B\n: is required","timestamp":"1731327300.0","comment_id":"1310014","upvote_count":"1","poster":"mldprasad"},{"upvote_count":"1","content":"Selected Answer: B\nB is correct","poster":"CristinaDev","timestamp":"1727336220.0","comment_id":"1289340"}],"answer_images":[],"answer_ET":"C"},{"id":"LCxu20K3Q00qBbh6niPc","exam_id":194,"timestamp":"2025-03-20 19:47:00","question_text":"What will happen when you attempt to run the following code?\n//IMG//","topic":"5","isMC":true,"discussion":[{"poster":"akumo","comment_id":"1401271","content":"Selected Answer: D\nD. The code will raise the SyntaxError exception.","upvote_count":"2","timestamp":"1742496420.0"}],"answers_community":["D (100%)"],"choices":{"C":"The code will raise the ValueError exception.","B":"The code will raise the AttributeError exception.","D":"The code will raise the SyntaxError exception.","A":"The code will raise the TypeError exception.","E":"The code will print Hello, World! tothe console."},"answer":"D","question_images":["https://img.examtopics.com/pcep-30-02/image449.png"],"unix_timestamp":1742496420,"question_id":272,"answer_images":[],"url":"https://www.examtopics.com/discussions/python-institute/view/169576-exam-pcep-30-02-topic-5-question-3-discussion/","answer_description":"","answer_ET":"D"},{"id":"5m1T6sqbezqpuVhxusGM","timestamp":"2025-03-25 15:36:00","choices":{"C":"1 | 4.0","A":"1 | Wrong value.","D":"1 | Error.Error.Error.","B":"1 | Do not divide by zero!"},"answer_ET":"C","answer_images":[],"question_id":273,"unix_timestamp":1742913360,"answers_community":["C (100%)"],"exam_id":194,"answer_description":"","question_text":"What is the output of the following program if the user enters kangaroo at the first prompt and 0 at the second prompt?\n//IMG//","discussion":[{"comment_id":"1410070","upvote_count":"1","timestamp":"1742913360.0","poster":"Donny_575","content":"Selected Answer: C\nC. 1 | 4.0\nExplanation:\n>> first_prompt = input(...) #\"kangaroo\"\na = len(first_prompt) # a = 8\n>> second_prompt = input(...) # \"0\"\nb = len(second_prompt) * 2 # b = 1 * 2 = 2\nprint(a / b) # 8 / 2 = 4.0"}],"topic":"5","question_images":["https://img.examtopics.com/pcep-30-02/image451.png"],"url":"https://www.examtopics.com/discussions/python-institute/view/169834-exam-pcep-30-02-topic-5-question-4-discussion/","isMC":true,"answer":"C"},{"id":"PppiACfqtzX5qvBlzCt8","topic":"5","url":"https://www.examtopics.com/discussions/python-institute/view/169578-exam-pcep-30-02-topic-5-question-5-discussion/","question_id":274,"unix_timestamp":1742496540,"answer":"C","choices":{"A":"must be the first one.","C":"must be the last one.","B":"cannot be used if any named block has been used.","D":"can be placed anywhere."},"timestamp":"2025-03-20 19:49:00","discussion":[{"poster":"Donny_575","comment_id":"1410072","content":"Selected Answer: C\nC. must be the last one.\nExplanation: When you write multiple except blocks, the unnamed except: block (also called a bare except) is used to catch any exception not already caught by the previous named ones. But it must come after all the specific exceptions, because otherwise Python won’t even look at the named ones — the unnamed one would catch everything first.","timestamp":"1742913600.0","upvote_count":"1"},{"content":"Selected Answer: C\nC. must be the last one.","timestamp":"1742496540.0","poster":"akumo","comment_id":"1401273","upvote_count":"2"}],"question_text":"The unnamed except block ...","isMC":true,"answer_ET":"C","answer_description":"","exam_id":194,"answer_images":[],"answers_community":["C (100%)"],"question_images":[]},{"id":"JvT8J14P1bSMl8Q2iDE0","answer_ET":"A","topic":"5","timestamp":"2025-03-25 15:48:00","question_text":"What is the output of the following code?\n//IMG//","answers_community":["A (100%)"],"isMC":true,"question_images":["https://img.examtopics.com/pcep-30-02/image454.png"],"url":"https://www.examtopics.com/discussions/python-institute/view/169836-exam-pcep-30-02-topic-5-question-6-discussion/","answer_description":"","answer":"A","question_id":275,"discussion":[{"timestamp":"1742914080.0","poster":"Donny_575","upvote_count":"1","content":"Selected Answer: A\nA. 1 | Very very bad input...\nExplanation: input values are captured as strings. Input of 5 = '5'\n'5' / '5' results in TypeError: unsupported operand type(s) for /: 'str' and 'str' because strings can’t be divided. TypeError: = \"Very very bad input...\"","comment_id":"1410077"}],"exam_id":194,"unix_timestamp":1742914080,"answer_images":[],"choices":{"A":"1 | Very very bad input...","B":"1 | Bad input...","C":"1 | Very bad input...","D":"1 | Booo!"}}],"exam":{"isMCOnly":true,"provider":"Python-institute","numberOfQuestions":330,"id":194,"name":"PCEP-30-02","isBeta":false,"isImplemented":true,"lastUpdated":"12 Apr 2025"},"currentPage":55},"__N_SSP":true}