{"pageProps":{"questions":[{"id":"30dOC0ugo8E6yy6LBw6P","answer":"B","answer_images":[],"choices":{"B":"The first matching branch.","A":"The last matching branch.","C":"Any of the matching branches."},"unix_timestamp":1742496060,"timestamp":"2025-03-20 19:41:00","isMC":true,"question_text":"Which of the approachable except: branches is taken into consideration when an exception occurs?","question_images":[],"exam_id":194,"answer_ET":"B","topic":"5","answer_description":"","url":"https://www.examtopics.com/discussions/python-institute/view/169575-exam-pcep-30-02-topic-5-question-1-discussion/","answers_community":["B (100%)"],"question_id":261,"discussion":[{"content":"Selected Answer: B\nB. The first matching branch.\nExplanation: When an exception occurs and multiple except branches are present, Python checks them in order, top to bottom, and executes the first one that matches the type of the exception.","upvote_count":"1","comment_id":"1410064","poster":"Donny_575","timestamp":"1742912640.0"},{"comment_id":"1401268","poster":"akumo","upvote_count":"2","timestamp":"1742496060.0","content":"Selected Answer: B\nB. The first matching branch."}]},{"id":"8kVbEM6R4N6tYMf6NQfz","answer_description":"","answers_community":["C (100%)"],"discussion":[{"comment_id":"1401279","upvote_count":"1","content":"Selected Answer: C\ntry:\n # risky code that might raise an exception\n x = 1 / 0 # This will raise a ZeroDivisionError\n\nexcept ZeroDivisionError:\n # handle the error here\n print(\"You can't divide by zero!\")","poster":"akumo","timestamp":"1742497320.0"}],"exam_id":194,"isMC":true,"unix_timestamp":1742497320,"question_id":262,"question_images":[],"timestamp":"2025-03-20 20:02:00","answer_images":[],"url":"https://www.examtopics.com/discussions/python-institute/view/169580-exam-pcep-30-02-topic-5-question-11-discussion/","answer_ET":"C","question_text":"The part of your code where you think an exception may occur should be placed inside:","answer":"C","topic":"5","choices":{"C":"the try: branch","A":"the except: branch","B":"the exception: branch"}},{"id":"6IrseqdE9zqD4ff20tkY","answer_images":[],"topic":"5","exam_id":194,"timestamp":"2025-03-20 20:05:00","url":"https://www.examtopics.com/discussions/python-institute/view/169581-exam-pcep-30-02-topic-5-question-12-discussion/","question_images":["https://img.examtopics.com/pcep-30-02/image464.png"],"unix_timestamp":1742497500,"answer_description":"","answer_ET":"D","answer":"D","question_id":263,"discussion":[{"comment_id":"1401281","upvote_count":"1","timestamp":"1742497500.0","poster":"akumo","content":"Selected Answer: D\nD. The program will cause a ValueError exception. there is no 0 index inside tuple"}],"question_text":"What is the expected behavior of the following program?\n//IMG//","isMC":true,"choices":{"A":"The program will cause a AttributeError exception.","D":"The program will cause a ValueError exception.","B":"The program will cause a SyntaxError exception.","E":"The program will cause a TypeError exception.","C":"The program will output 1 to the screen."},"answers_community":["D (100%)"]},{"id":"nNjG32zmLJAAuhZNciZJ","url":"https://www.examtopics.com/discussions/python-institute/view/169582-exam-pcep-30-02-topic-5-question-15-discussion/","isMC":true,"answer_images":[],"question_id":264,"question_images":[],"unix_timestamp":1742497860,"question_text":"The following statement ...\nassert x == 0","choices":{"C":"is erroneous.","D":"will stop the program if x is not equal to 0.","B":"has no effect.","A":"will stop the program if x is equal to 0."},"discussion":[{"timestamp":"1743411240.0","upvote_count":"1","comment_id":"1414242","content":"Selected Answer: D\nD. will stop the program if x is not equal to 0. \nExplanation: The assert statement in Python is used to test if a condition is True. If itâ€™s False, it raises an AssertionError and stops the program.","poster":"Donny_575"},{"content":"Selected Answer: D\nD. will stop the program if x is not equal to 0.","timestamp":"1742497860.0","upvote_count":"2","comment_id":"1401285","poster":"akumo"}],"answers_community":["D (100%)"],"exam_id":194,"answer":"D","answer_ET":"D","topic":"5","answer_description":"","timestamp":"2025-03-20 20:11:00"},{"id":"MLEYKeXIjmTilsotKf0w","topic":"5","question_id":265,"answer_ET":"C","answer":"C","question_images":["https://img.examtopics.com/pcep-30-02/image476.png"],"answer_description":"","isMC":true,"timestamp":"2025-03-20 20:15:00","unix_timestamp":1742498100,"answers_community":["C (100%)"],"choices":{"C":"1","B":"3","A":"The code is erroneous.","D":"2"},"discussion":[{"upvote_count":"1","content":"Selected Answer: C\nThe first except BaseException block is the first match, so it prints 1 and no further exceptions are handled. Therefore, the output is 1.","comment_id":"1401286","poster":"akumo","timestamp":"1742498100.0"}],"answer_images":[],"exam_id":194,"question_text":"What is the expected output of the following code?\n//IMG//","url":"https://www.examtopics.com/discussions/python-institute/view/169583-exam-pcep-30-02-topic-5-question-16-discussion/"}],"exam":{"id":194,"isMCOnly":true,"name":"PCEP-30-02","lastUpdated":"12 Apr 2025","provider":"Python-institute","isImplemented":true,"isBeta":false,"numberOfQuestions":330},"currentPage":53},"__N_SSP":true}