{"pageProps":{"questions":[{"id":"8t3pFRm0ahzw0Y3eF5Nk","url":"https://www.examtopics.com/discussions/oracle/view/84847-exam-1z0-808-topic-1-question-186-discussion/","exam_id":399,"isMC":true,"answer_images":["https://www.examtopics.com/assets/media/exam-media/04353/0020700002.png"],"question_text":"Given the code fragment:\n//IMG//\n\nWhat is the result?","answer":"D","answers_community":["D (100%)"],"unix_timestamp":1665318060,"question_images":["https://www.examtopics.com/assets/media/exam-media/04353/0020700001.png"],"answer_ET":"D","answer_description":"","question_id":96,"topic":"1","choices":{"C":"2 : 7 : 0","A":"2 : 7 : 3","D":"7 : 2 : 3","B":"7 : 7 : 9"},"timestamp":"2022-10-09 14:21:00","discussion":[{"timestamp":"1729973100.0","poster":"carloswork","content":"Selected Answer: D\nAnswer is D.\n\nTo test:\n\npublic static void main(String[] args) {\n int a = 3;\n int b = 2;\n int c = 1;\n int r1 = a * b / c + 1;\n int r2 = a / b * c + 1;\n int r3 = a * (b / (c + 1));\n System.out.println(r1 + \" : \" + r2 + \" : \" + r3);\n}","comment_id":"704991","upvote_count":"1"},{"upvote_count":"1","timestamp":"1728476460.0","content":"Selected Answer: D\nThe correct answer is the letter D, remembering that we can divide \"int\" types even if there is leftover, dividing 3 by 2 would give \"1.5\" but as the whole number it cuts the decimal places getting \"1\" and making the code compile normally. Just doing the result of \"r1\" and \"r2\" you can already have the result without having to calculate \"r3\", the OCA test asks questions like this for you to waste time with distractors and time in a test that requires attention in every question is gold.","poster":"iSnover","comment_id":"690160"}]},{"id":"3H4npIPLVGcxQMDCwujM","question_text":"Given:\n//IMG//\n\nWhich action fixes the compiler error?","question_images":["https://www.examtopics.com/assets/media/exam-media/04353/0020800001.png"],"answer_description":"","choices":{"C":"At line 2, replace throws LogFileException with throws AccessViolationException","A":"At line 17, add throws AccessViolationException","D":"At line 7, insert throw new LogFileException ();","B":"At line 13, add throws LogFileException"},"answers_community":["B (100%)"],"topic":"1","timestamp":"2022-09-13 10:37:00","answer_ET":"B","answer_images":[],"exam_id":399,"unix_timestamp":1663058220,"discussion":[{"poster":"iSnover","content":"Selected Answer: B\nThe correct answer is the letter B, in cases of EXCEPTIONS you need to declare in the constructor \"throws LogFileException\". In the case of a RuntimeException you don't need to.","comment_id":"690166","timestamp":"1728476880.0","upvote_count":"3"},{"poster":"shivkumarx","timestamp":"1726216620.0","comment_id":"667789","upvote_count":"4","content":"Answer is B\nTested:\npublic class App {\n public static void main(String[] args) {\n App obj = new App();\n try {\n obj.open();\n obj.process();\n throw new LogFileException();\n }\n catch (Exception e) {\n // TODO: handle exception\n }\n }\n void process() throws LogFileException{\n System.out.println(\"Processed\");\n throw new LogFileException();\n }\n void open() {\n System.out.println(\"Opened\");\n throw new AccessViolationException();\n }\n}\nclass LogFileException extends Exception {}\nclass AccessViolationException extends RuntimeException {}"}],"url":"https://www.examtopics.com/discussions/oracle/view/81959-exam-1z0-808-topic-1-question-187-discussion/","answer":"B","isMC":true,"question_id":97},{"id":"GmrI52GDtt9ES9BM9qLf","question_images":["https://www.examtopics.com/assets/media/exam-media/04353/0020900001.png"],"topic":"1","answers_community":["D (100%)"],"answer_images":[],"timestamp":"2022-10-09 14:32:00","url":"https://www.examtopics.com/discussions/oracle/view/84850-exam-1z0-808-topic-1-question-188-discussion/","exam_id":399,"question_id":98,"answer_description":"","unix_timestamp":1665318720,"question_text":"Given the code fragment:\n//IMG//\n\nWhat is the result?","choices":{"C":"1 2 3 0 0 1 2 3","D":"1 2 3 1 2 3","B":"An Exception is thrown at run time.","A":"1 2 3 0 0 1 2 3 0 0"},"isMC":true,"answer":"D","answer_ET":"D","discussion":[{"content":"For Test:\n\npublic static void main(String[] args) {\n int array1[] = {1, 2, 3};\n int array2[] = new int[5];\n array2 = array1;\n for (int i : array2) {\n System.out.print(i + \" \");\n }\n System.out.println();\n int array3[] = new int[3];\n array3 = array2;\n for (int i : array3) {\n System.out.print(i + \" \");\n }\n }","timestamp":"1732113180.0","upvote_count":"2","comment_id":"722699","poster":"epicbrozo86"},{"comment_id":"690168","timestamp":"1728477120.0","poster":"iSnover","content":"Selected Answer: D\nThe answer is the letter D and there's not much to point out, when you reference an array that you had already instantiated along with arguments to another after the declaration, the variable starts to point to the other one, so it prints 1 2 3 1 2 3","upvote_count":"4"}]},{"id":"iGBu17NVbqH9PF7eTUfF","url":"https://www.examtopics.com/discussions/oracle/view/84851-exam-1z0-808-topic-1-question-189-discussion/","answer_ET":"B","timestamp":"2022-10-09 14:34:00","exam_id":399,"question_id":99,"question_images":["https://www.examtopics.com/assets/media/exam-media/04353/0021100001.png"],"unix_timestamp":1665318840,"answer_images":["https://www.examtopics.com/assets/media/exam-media/04353/0021200001.jpg"],"answer_description":"","choices":{"B":"The program fails compile due to the unhandled E1 exception.","A":"The program prints m1.Accessed.","D":"The program fails to compile due to the unhandled E2 exception.","C":"The program prints m2.Accessed."},"answers_community":["B (100%)"],"question_text":"Examine:\n//IMG//\n\nWhich statement is true?","isMC":true,"discussion":[{"comment_id":"1060013","timestamp":"1730489040.0","content":"Selected Answer: B\nTo test:\n\nclass E1 extends Exception {\n}\n\nclass E2 extends RuntimeException {\n}\n\npublic class App {\n\n public void m1() {\n System.out.println(\"m1.Accessed.\");\n throw new E1();\n }\n\n public void m2() {\n System.out.println(\"m2.Accessed.\");\n throw new E2();\n }\n\n public static void main(String[] args) {\n int level = 1;\n App obj = new App();\n if (level <= 5 && level >= 3) {\n obj.m1();\n } else {\n obj.m2();\n }\n }\n}","upvote_count":"1","poster":"Bear4TW"},{"upvote_count":"1","content":"Selected Answer: B\nThe correct answer is the letter B, in cases of EXCEPTIONS you need to declare in the constructor \"throws E1\". In the case of a RuntimeException you don't need to.","poster":"iSnover","timestamp":"1696854840.0","comment_id":"690170"}],"answer":"B","topic":"1"},{"id":"FKdtMBnl7qTujnCZQJK0","answer":"D","question_text":"Given the code fragment:\n//IMG//\n\nWhat is the result?\nA.\n//IMG//\n\nB. Compilation fails only at line n1.\nC. Compilation fails only at line n2.\nD. Compilation fails only at line n3.\nE. Compilation fails at both line n2 and line n3.","url":"https://www.examtopics.com/discussions/oracle/view/80263-exam-1z0-808-topic-1-question-19-discussion/","isMC":false,"question_id":100,"answer_ET":"D","timestamp":"2022-09-05 10:00:00","question_images":["https://www.examtopics.com/assets/media/exam-media/04353/0002000002.png","https://www.examtopics.com/assets/media/exam-media/04353/0002100001.png"],"answer_images":[],"answer_description":"","unix_timestamp":1662364800,"topic":"1","discussion":[{"comment_id":"659895","upvote_count":"14","content":"I think the correct answer is C. The exception for readCard() must be caught or declared to be thrown.","timestamp":"1662364800.0","poster":"RoxyFoxy"},{"timestamp":"1743760680.0","content":"Answer is 'C'.","comment_id":"1460056","poster":"surya8833","upvote_count":"1"},{"content":"Answer is C, exception on readCard is not handled\njava: unreported exception java.lang.Exception; must be caught or declared to be thrown","timestamp":"1737470340.0","upvote_count":"2","comment_id":"1344193","poster":"TheeOne"},{"comment_id":"1343811","poster":"TheeOne","upvote_count":"1","content":"answer is A, code compiles and prints","timestamp":"1737399240.0"},{"timestamp":"1730667900.0","comment_id":"1306645","poster":"MPignaProTech","content":"Correct answer is C. Exception must be verified. RunTimeException is not mandotory to be verified","upvote_count":"1"},{"comment_id":"1295061","poster":"joeMP","content":"Correct answer is C. Exception must be verified. RunTimeException is not mandotory to be verified","timestamp":"1728465600.0","upvote_count":"1"},{"timestamp":"1699014360.0","upvote_count":"2","comment_id":"1061423","poster":"z24134","content":"checked exception needs to be thrown"},{"content":"Answer should be C","timestamp":"1697613000.0","upvote_count":"1","poster":"yefiw","comment_id":"1046660"},{"timestamp":"1697033400.0","upvote_count":"1","comment_id":"1040730","poster":"arjunrawatirissoftware","content":"Answer - C"},{"comment_id":"993012","upvote_count":"2","timestamp":"1693307460.0","content":"Answer is C. Compilation fails only at line n2.\n\\\\Code\n\npublic class Test {\n\nvoid readCard(int cardNo) throws Exception {\nSystem.out.println(\"Reading Card\");\n}\n\nvoid checkCard(int cardNo) throws RuntimeException {\nSystem.out.println(\"Checking Card\");\n}\n\npublic static void main(String[] args) {\nTest ex = new Test();\nint cardNo = 12344;\nex.readCard(cardNo);\nex.checkCard(cardNo);\n}\n}","poster":"DriftKing"},{"upvote_count":"1","timestamp":"1692968280.0","content":"C is the correct one, because when method throw checked exception, u have to handle it.","poster":"duydn","comment_id":"990079"},{"content":"Answer is C\n\nA, compile error (Does not print)\nB, The method itself is not wrong, you just have to try/catch\nC, Did not catch the Exception\nD, Last line won't fail because it's method is runtime and runtime doesn't happen if it doesn't even compile.","timestamp":"1692596160.0","upvote_count":"2","poster":"a_really_reliable_programmer","comment_id":"986231"},{"comment_id":"982345","content":"C is correct","timestamp":"1692176100.0","upvote_count":"1","poster":"Sreeni_A"},{"comment_id":"971434","upvote_count":"1","content":"C, Unhandled exception: java.lang.Exception ... Runtime is unchecked exception","poster":"jlicini","timestamp":"1691092740.0"},{"content":"C is the correct","timestamp":"1691082480.0","upvote_count":"1","comment_id":"971336","poster":"dsms"},{"content":"Answer is C. Checked Exceptions should be handled or declared, in this case the problem is that we missed to declare the Exception in main method. So in order your code to pass the compilation, you should add at the main method \"throws Exception\".","timestamp":"1684079460.0","upvote_count":"1","comment_id":"897679","poster":"billy_the_kid"},{"comment_id":"857675","poster":"Vicky_65","upvote_count":"2","timestamp":"1680333960.0","content":"The answer is option C.Because checked exception should be declared or handle in main method for readcard method."},{"timestamp":"1676241480.0","content":"The answer should be C. The compilation error can be removed by doing this - class Test {\nvoid readCard (int cardNo) throws Exception {\nSystem.out.println(\"Reading Card\");\n}\nvoid checkCard (int cardNo) throws RuntimeException {\nSystem.out.println(\"Checking Card\");\n}\npublic static void main (String[] args) throws Exception {\nTest ex = new Test();\nint cardNo = 12344;\nex. readCard (cardNo) ;\nex. checkCard (cardNo);\n}\n}","comment_id":"806871","poster":"Shad657","upvote_count":"1"},{"poster":"Ankit1010","timestamp":"1675766940.0","upvote_count":"2","comment_id":"800773","content":"C is the correct answer"},{"upvote_count":"2","comment_id":"752026","content":"Vote C: RuntimeException no need trycatch or throws","timestamp":"1671612480.0","poster":"haisaco"},{"poster":"willokans","upvote_count":"1","timestamp":"1669197120.0","comment_id":"725038","content":"Answer is C\nUnhandled Exception in line n3"},{"comment_id":"720678","content":"c is ans","upvote_count":"1","poster":"anmoldev2java","timestamp":"1668704580.0"},{"timestamp":"1666123320.0","poster":"carloswork","upvote_count":"2","comment_id":"698491","content":"Answer is C.\n\nIt can be tested and observed with the code below\n\npublic class Test {\n\n void Checked_Exception () throws Exception {\n System.out.println(\"Checked_Exception\");\n }\n \n void UnChecked_Exception () throws RuntimeException {\n System.out.println(\"UnChecked_Exception\");\n }\n \n public static void main(String[] args) {\n Test t = new Test();\n t.Checked_Exception();\n t.UnChecked_Exception();\n }\n}"},{"upvote_count":"2","content":"Tested.Correct answer is C.","comment_id":"693245","timestamp":"1665591480.0","poster":"UAK94"},{"comment_id":"682328","upvote_count":"2","poster":"Rdharma","timestamp":"1664424840.0","content":"correct answer is C"},{"timestamp":"1664421360.0","poster":"baledevit","upvote_count":"2","content":"The correct answer is C. Only RuntimeException and any exceptions that descend from it should not be checked with try-catch.\n\nAll the others must be handled otherwise the compilation fails.","comment_id":"682300"},{"timestamp":"1662890340.0","poster":"shivkumarx","comment_id":"666000","content":"Correct answer is definitely C","upvote_count":"4"}],"answers_community":[],"exam_id":399}],"exam":{"isImplemented":true,"numberOfQuestions":234,"lastUpdated":"12 Apr 2025","id":399,"provider":"Oracle","name":"1z0-808","isBeta":false,"isMCOnly":false},"currentPage":20},"__N_SSP":true}